# Generated by Django 5.0.4 on 2025-09-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_alter_comment_publication_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="name",
            new_name="title",
        ),
    ]
