# Generated by Django 5.0.4 on 2024-08-07 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_leafseeuser_is_banned_subscription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leafseeuser",
            name="password_change_date",
            field=models.DateTimeField(
                default=datetime.date.today, verbose_name="last password change date"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
