# Generated by Django 5.0.4 on 2024-06-10 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=7500)),
                ("publication_date", models.DateField(auto_now_add=True)),
                (
                    "is_changed",
                    models.BooleanField(default=False, verbose_name="is changed"),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="is delete"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commented_comment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="videos.comment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_rating",
                    models.CharField(
                        choices=[("l", "Like"), ("d", "Dislike")], max_length=1
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="videos.comment"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rated_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="ratings",
            field=models.ManyToManyField(
                through="videos.CommentRating", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("duration", models.DurationField()),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(max_length=5000)),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("preview_image", models.ImageField(upload_to="")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="commented_video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="videos.video",
            ),
        ),
        migrations.CreateModel(
            name="VideoRatedViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_rating",
                    models.CharField(
                        choices=[("l", "Like"), ("d", "Dislike"), ("n", "None")],
                        default="n",
                        max_length=1,
                    ),
                ),
                ("viewing_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viewed_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="videos.video"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="video",
            name="rated_views",
            field=models.ManyToManyField(
                through="videos.VideoRatedViews", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="VideoTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_videos",
                        to="videos.tag",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="videos.video"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="video",
            name="tags",
            field=models.ManyToManyField(through="videos.VideoTag", to="videos.tag"),
        ),
        migrations.AddConstraint(
            model_name="commentrating",
            constraint=models.UniqueConstraint(
                fields=("comment", "user"), name="unique_comment_rating"
            ),
        ),
        migrations.AddConstraint(
            model_name="videoratedviews",
            constraint=models.UniqueConstraint(
                fields=("video", "user"), name="unique_video_rating_view"
            ),
        ),
        migrations.AddConstraint(
            model_name="videotag",
            constraint=models.UniqueConstraint(
                fields=("video", "tag"), name="unique_video_tag"
            ),
        ),
    ]
