# Generated by Django 5.0.4 on 2024-08-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_rename_ratings_comment_rated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="publication_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="upload_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="videoratedviews",
            name="viewing_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
