services:
    nginx:
        container_name: leafsee-simple-nginx
        image: nginx:1.27.2-bookworm
        restart: unless-stopped
        volumes:
            - ../../nginx_configs/dev/nginx.conf:/etc/nginx/nginx.conf:ro
            - ../../media:/app/media:ro
            # Backend static files
            - ../../backend/staticfiles:/app/staticback:ro
            # General static files
            - ../../static_general:/app/staticgen:ro
        ports:
            - 5438:80
        extra_hosts:
            - "host.docker.internal:host-gateway"
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 1G

    postgres:
        container_name: leafsee-simple-postgresql
        image: postgres:16.2-bookworm
        restart: unless-stopped
        environment:
            POSTGRES_DB: "leafsee"
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "pass"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - leafsee-simple-postgres-data:/var/lib/postgresql/data
        ports:
            - "5435:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U root -d pass"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 4G
        networks:
            - postgres

    pgadmin:
        container_name: leafsee-simple-pgadmin
        image: dpage/pgadmin4:8.5
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: "root@domain.com"
            PGADMIN_DEFAULT_PASSWORD: "pass"
            # Run pgadmin in desktop mode, skip authentication
            PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
            - leafsee-simple-pgadmin-data:/var/lib/pgadmin
        ports:
            - "5440:80"
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G
        networks:
            - postgres

volumes:
    leafsee-simple-postgres-data:
    leafsee-simple-pgadmin-data:

networks:
    postgres:
        driver: bridge
