# Generated by Django 5.0.4 on 2024-04-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_leafseeuser_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leafseeuser",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"unique": "A user with that e-mail already exists."},
                max_length=140,
                unique=True,
                verbose_name="email",
            ),
        ),
    ]
